# Generated by Django 5.2.5 on 2025-08-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief project description', null=True)),
                ('project_type', models.CharField(choices=[('personal', 'Personal'), ('client', 'Client')], default='personal', help_text='Project type', max_length=20)),
                ('category', models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('mixed', 'Mixed')], default='mixed', help_text='Project category', max_length=20)),
                ('client_name', models.CharField(blank=True, help_text='Leave empty for personal projects', max_length=255, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Project creation date')),
                ('updated_at', models.DateField(auto_now=True, help_text='Project last update date')),
                ('is_published', models.BooleanField(default=True, help_text='Is the project visible on the site?')),
                ('live_url', models.URLField(blank=True, help_text='Project live URL', null=True)),
                ('repo_url', models.URLField(blank=True, help_text='Project repository URL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/media/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the media', max_length=255, null=True)),
                ('project', models.ForeignKey(help_text='Associated project', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='tags', to='core.project')),
            ],
        ),
    ]
