# Generated by Django 5.2.5 on 2025-08-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('client', 'Client'), ('community', 'Community'), ('open_source', 'Open Source')], default='personal', help_text='Project type', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='Unique URL-friendly identifier <i>(auto-generated)</i>', unique=True),
        ),
    ]
