# Generated by Django 5.2.5 on 2025-08-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_project_type_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='projects',
            field=models.ManyToManyField(related_name='tags', to='core.project'),
        ),
    ]
