# Generated by Django 5.2.5 on 2025-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_projecttag_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('contract', 'Contract'), ('community', 'Community'), ('open_source', 'Open Source')], default='personal', help_text='Project type', max_length=20),
        ),
    ]
