# Generated by Django 5.2.5 on 2025-08-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmedia',
            options={'ordering': ['project__title'], 'verbose_name': 'Project Media', 'verbose_name_plural': 'Project Media'},
        ),
        migrations.AlterModelOptions(
            name='projecttag',
            options={'ordering': ['name'], 'verbose_name': 'Project Tag', 'verbose_name_plural': 'Project Tags'},
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(help_text='Achievement description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('link', models.URLField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, help_text='Achievement last update date')),
                ('is_published', models.BooleanField(default=True, help_text='Is the achievement visible on the site?')),
                ('tags', models.ManyToManyField(blank=True, to='core.projecttag')),
            ],
            options={
                'ordering': ['-created_at', '-event_date'],
            },
        ),
    ]
