# Generated by Django 5.2.5 on 2025-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_projectmedia_options_alter_projecttag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Project Tag',
                'verbose_name_plural': 'Project Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='core.tag'),
        ),
        migrations.DeleteModel(
            name='ProjectTag',
        ),
    ]
