# Generated by Django 5.2.5 on 2025-08-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag_project_tags_alter_achievement_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
