# Generated by Django 5.2.5 on 2025-08-21 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Is the skill visible on the site?'),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateField(auto_now=True, help_text='Skill last update date'),
        ),
    ]
