# Generated by Django 5.2.5 on 2025-08-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_skill_created_at_skill_is_published_skill_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Achievement last update date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Project creation date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Project last update date'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Skill last update date'),
        ),
    ]
