# Generated by Django 5.2.5 on 2025-09-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main story title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle or tagline', max_length=300)),
                ('content', models.TextField(help_text='Main story content')),
                ('period', models.CharField(help_text="Time period (e.g., '2020-2023', 'Early 2024')", max_length=100)),
                ('is_published', models.BooleanField(default=True, help_text='Publish this story')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
