# Generated by Django 5.2.5 on 2025-09-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional story image', null=True, upload_to='stories/'),
        ),
    ]
