# Generated by Django 5.2.5 on 2025-09-16 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent story if this is a sub-topic', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substories', to='core.story'),
        ),
    ]
