# Generated by Django 5.2.5 on 2025-09-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_story_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-created_at', '-event_start_date']},
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='event_date',
            new_name='event_start_date',
        ),
        migrations.AddField(
            model_name='achievement',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
