# Generated by Django 5.2.5 on 2025-09-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('contract', 'Contract'), ('community', 'Community'), ('open_source', 'Open Source'), ('hackathon', 'Hackathon')], default='personal', help_text='Project type', max_length=20),
        ),
    ]
