# Generated by Django 5.2.5 on 2025-09-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
